Fixing build errors for 13th March 2023 10AM GMT canary
Almost there, just have an LNK2019 error relating to emulator.cc

also commenting out a MessageBox call in winkey_input_driver.cc due to error C2440: 'type cast': cannot convert from 'overloaded-function' to 'xe::ui::Win32Window *'
Won't have notifications about failing to load bindings.ini file